### ISSUE TITLE
Block list doesn't save block using nested block list

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#10947]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.1

### Bug summary

When adding a block element to block list, and the block contains a nested block list without items, the block is removed on save.

![Stm3r377u4](https://user-images.githubusercontent.com/2919859/130763069-200717fb-0f8b-4941-a2e7-d371b04a37ed.gif)

### Steps to reproduce

- Create a block list and add a block element in the datatype configuration.
- For the created block element an a property using block list property editor.
- Add a block element to the nested block list editor.
- Add the main block to the block list and add an empty or no items in the nested block list. On save the added block is removed from the block list.

Even if I fill the properties in the nested block with image, heading and link it is removed on save.

This used to work and on another project on v8.14.3 it does work.

**Comment by bjarnef** [comment]
This is on Umbraco Cloud btw.

I just deployed this changed to live environment, where it does seem to work.

I noticed this console error on local environment, so I wonder if something funky is going on with Umbraco Deploy. @nul800sebastiaan @AndyButland 

![chrome_3DFrjSYOXo](https://user-images.githubusercontent.com/2919859/130766644-4d225100-0ded-4225-a3cc-e34d7a63a1bf.png)

**Comment by bjarnef** [comment]
@AndyButland if I comment out this part in Umbraco Deploy I can save the block list with a block used nested block element.

![image](https://user-images.githubusercontent.com/2919859/130768143-fc3e9a8d-32d0-4e54-b80d-55bf820a62e1.png)

![image](https://user-images.githubusercontent.com/2919859/130768300-d53167a8-a2d3-40a3-affa-6f56ff061f6b.png)

**Comment by bjarnef** [comment]
Okay, strange enough I can't reproduce it now after commented out that that in deploy and added the Image Grid block.
When I removed the commented part in deploy and try again it seems to work.

Not sure if CDF bundle wasn't updated or if it in someway is related to https://github.com/umbraco/Umbraco-CMS/issues/10910

**Comment by nul800sebastiaan** [comment]
This is indeed exactly like what we fixed for #10910 - as soon as your app pool recycles it reloads the caches and new properties can save again. Deploying to live recycles the app pool. 8.15.3 is coming Tuesday so you'll be upgraded. Until then.. so sorry for the inconvenience!  

So just remember when you add new properties to blocks, for now you will need to recycle to get the content to stick, or grab a nightly build of `v8/8.15`.

**Comment by bjarnef** [comment]
@nul800sebastiaan yeah, I actually recycled the app pool a few times, so it could very well be the same issue.

**Comment by bjarnef** [comment]
I just added a settings element type to the nested block and am getting these errors and the six existing blocks are not shown.

![chrome_MdAsxFcoGu](https://user-images.githubusercontent.com/2919859/130794402-2ffee4a2-8930-4247-a83b-0632d2c4de2c.png)

I tried recycling app pool, increasing CDF version, clear browser cache, but still getting the errors.
When I removed the Settings block from the block element in the block list configuration the blocks in the nested block list are shown again.

Does https://github.com/umbraco/Umbraco-CMS/issues/10910 solve this issue as well?
