### ISSUE TITLE
umbraco 9: imagesharp and custom virtual directory not working together

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#11580]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

Hello

Umbraco out-of-the-box seems to expect that media will reside in wwwroot, but our requirement (and I suspect many others too) is the need to store umbraco media in a custom directory (say a UNC network path) or even an azure blob for production.

I have registered a custom media directory as per https://our.umbraco.com/Documentation/Extending/FileSystemProviders/ but then the issue seems to become how to tell ImageSharp about that location too (for crops on the website frontend). We found a ImageSharp thread about doing this https://github.com/SixLabors/ImageSharp.Web/issues/135

Following both of the above ultimately seems to clash with each other as Umbraco middleware already registers Imagesharp in the start-up routine.

Is there a documented working solution or this? (anyone with a CD/automated deployment system will most likely need media to sit “outside” of the deployment package so that it “survives” deployments, so might be missing why this isn’t capability that more people are requesting?)

Thanks
Andrew

### Steps to reproduce

no additional info to ticket summary

**Comment by creativesuspects** [comment]
I'd also like to use a static content folder outside of wwwroot on an Umbraco 9 project. I've been able to get this working using a custom FileSystemProvider, but that breaks ImageSharp, as @shearer3000 has already mentioned. I've even tried implementing a custom IImageProvider, but I'm a bit confused as to how (or where) I should tell ImageSharp to use the custom IImageProvider since ImageSharp is already being registered as middleware by Umbraco itself.

**Comment by shearer3000** [comment]
are we missing something here @creativesuspects ? i wonder why we're the only ones requiring this? are we doing something wrong or is everyone else using an azure blog for all environments including dev and test? would be great to hear some insight / thoughts from someone at HQ. thanks

**Comment by creativesuspects** [comment]
I’m also curious to know why there aren’t more devs running into this issue. I’m developing solo and I need this to easily share media between local and staging environments. But I would imagine that devs working in teams especially would use a “shared folder” setup all the time.

I haven’t had time to really dive into the Azure Blob Storage solution yet. But by the looks of it you’d need quite a bit of code to get it working. For something that could be fixed with a simple virtual directory in IIS prior to v9...

It’s great that Umbraco 9 offers the IFileSystem interface, but it’s kind of useless when it breaks ImageSharp in the process.

**Comment by shearer3000** [comment]
Discord channel? no not sure what that is

**Comment by shearer3000** [comment]
hi @bergmania any insight from HQ on this? thanks

**Comment by bergmania** [comment]
Hi @shearer3000 ...

We have assigned time to look at this in our upcoming sprint.

You should be able to configure ImageSharp even that it is also added by Umbraco. Maybe by calling `services.Configure<T>()` or `services.AddImageSharp()`.

But hopefully we can make it easier :)

**Comment by creativesuspects** [comment]
> Hi @shearer3000 ...
> 
> We have assigned time to look at this in our upcoming sprint.
> 
> You should be able to configure ImageSharp even that it is also added by Umbraco. Maybe by calling `services.Configure<T>()` or `services.AddImageSharp()`.
> 
> But hopefully we can make it easier :)

I will test if (re)adding ImageSharp after initializing the FileSystemProvider makes a difference.

**Comment by bergmania** [comment]
I have something like this working.. Based on the two links you provided.. 

The important thing is that the `ImageSharpMiddleware ` are running before the `StaticFileMiddleware`. Otherwise the request are handled by the StaticFileMiddleware (and ignoring the query)

```cs
using System.IO;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Logging;
using SixLabors.ImageSharp.Web;
using SixLabors.ImageSharp.Web.DependencyInjection;
using SixLabors.ImageSharp.Web.Providers;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Core.IO;
using Umbraco.Cms.Infrastructure.DependencyInjection;
using Umbraco.Cms.Web.Common.ApplicationBuilder;
using IHostingEnvironment = Umbraco.Cms.Core.Hosting.IHostingEnvironment;

namespace UmbracoExamples.Composition
{
    public class SetMediaFileSystemComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            var rootPath = Path.Combine("C:", "storage", "umbracoMedia");
            
            builder.SetMediaFileSystem((factory) =>
            {
                IHostingEnvironment hostingEnvironment = factory.GetRequiredService<IHostingEnvironment>();
              
                var rootUrl = hostingEnvironment.ToAbsolute("/CustomPath");

                return new PhysicalFileSystem(
                    factory.GetRequiredService<IIOHelper>(),
                    hostingEnvironment,
                    factory.GetRequiredService<ILogger<PhysicalFileSystem>>(),
                    rootPath,
                    rootUrl);
            });

            var fileProvider = new PhysicalFileProvider(rootPath);
            builder.Services.Configure<UmbracoPipelineOptions>(options =>
                options.AddFilter(new UmbracoPipelineFilter(nameof(SetMediaFileSystemComposer))
                {
                    PrePipeline = app =>
                    {
                        app.UseImageSharp();
                        app.UseStaticFiles(new StaticFileOptions
                        {
                            FileProvider = fileProvider,
                            RequestPath = "/CustomPath"
                        });
                    }
                }));

            builder.Services.AddImageSharp().ClearProviders().AddProvider<CustomMediaPhysicalFileSystemProvider>();
         }
    }

    
    
    public class CustomMediaPhysicalFileSystemProvider : PhysicalFileSystemProvider
    {
        public CustomMediaPhysicalFileSystemProvider(
            IWebHostEnvironment environment,
            FormatUtilities formatUtilities) : base(UseCustomWebRootFileProvider(environment), formatUtilities)
        {
        }

        private static IWebHostEnvironment UseCustomWebRootFileProvider(IWebHostEnvironment environment)
        {
            return new CustomMediaWebHostEnvironment(environment);
        }
    }

    internal class CustomMediaWebHostEnvironment : IWebHostEnvironment
    {
        private readonly IWebHostEnvironment _environment;

        public CustomMediaWebHostEnvironment(IWebHostEnvironment environment)
        {
            _environment = environment;
            WebRootFileProvider = new PhysicalFileProvider(Path.Combine("C:", "storage", "umbracoMedia"));
        }

        public string ApplicationName
        {
            get => _environment.ApplicationName;
            set => _environment.ApplicationName = value;
        }

        public IFileProvider ContentRootFileProvider
        {
            get => _environment.ContentRootFileProvider;
            set => _environment.ContentRootFileProvider = value;
        }
        
        public string ContentRootPath
        {
            get => _environment.ContentRootPath;
            set => _environment.ContentRootPath = value;
        }
        public string EnvironmentName
        {
            get => _environment.EnvironmentName;
            set => _environment.EnvironmentName = value;
        }
        
        public string WebRootPath        
        {
            get => _environment.WebRootPath;
            set => _environment.WebRootPath = value;
        }
        public IFileProvider WebRootFileProvider { get; set; }
    }
}
```

**Comment by creativesuspects** [comment]
@bergmania Looking forward to test your code tomorrow!

**Comment by creativesuspects** [comment]
@bergmania I used your code to add ImageSharp followed by my custom FileSystemProvider, but I implemented the FileSystemProvider slightly different based on these comments:

https://github.com/SixLabors/ImageSharp.Web/issues/135#issuecomment-756491491
https://github.com/SixLabors/ImageSharp.Web/blob/master/src/ImageSharp.Web/Providers/PhysicalFileSystemProvider.cs

So on Development and Staging I'm loading media files from a shared Dropbox folder (outside of wwwroot) and on Production I'm using the default wwwroot/media location. The path for the Dropbox folder is configured in appsettings.Development.json and appsettings.Staging.json. The only issue I've noticed so far with this setup is that it seems physical media files that were added on Development are not being deleted when the media item is deleted on Staging and the recycle bin is emptied. When I upload and delete media items on the same environment the physical file does get deleted. So that's a weird one.

```
public class CustomMediaFileSystemComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        var rootPath = "";

        builder.SetMediaFileSystem((factory) =>
        {
            var webHostEnvironment = factory.GetRequiredService<IWebHostEnvironment>();
            var hostingEnvironment = factory.GetRequiredService<IHostingEnvironment>();
            var rootUrl = hostingEnvironment.ToAbsolute("~/media");

            rootPath = hostingEnvironment.MapPathWebRoot("~/media");

            if (webHostEnvironment.IsProduction() == false)
            {
                var mediaSettings = new MediaSettings();
                builder.Config.GetSection("Application").GetSection("Media").Bind(mediaSettings);

                if (mediaSettings.RootPath.HasValue())
                {
                    rootPath = mediaSettings.RootPath;
                }
            }

            return new PhysicalFileSystem(
                factory.GetRequiredService<IIOHelper>(),
                hostingEnvironment,
                factory.GetRequiredService<ILogger<PhysicalFileSystem>>(),
                rootPath,
                rootUrl);
        });

        builder.Services.Configure<UmbracoPipelineOptions>(options =>
            options.AddFilter(new UmbracoPipelineFilter(nameof(CustomMediaFileSystemComposer))
            {
                PrePipeline = app =>
                {
                    var fileProvider = new PhysicalFileProvider(rootPath);

                    app.UseImageSharp();
                    app.UseStaticFiles(new StaticFileOptions
                    {
                        FileProvider = fileProvider,
                        RequestPath = "/media"
                    });
                }
            }));

        builder.Services.AddImageSharp().ClearProviders().AddProvider<CustomMediaFileSystemProvider>();
    }
}

public class CustomMediaFileSystemProvider : IImageProvider
{
    private readonly IFileProvider fileProvider;
    private readonly FormatUtilities formatUtilities;
    private readonly IConfiguration config;

    public CustomMediaFileSystemProvider(
        IWebHostEnvironment environment,
        FormatUtilities formatUtilities,
        IConfiguration config)
    {
        this.formatUtilities = formatUtilities ?? throw new ArgumentNullException(nameof(formatUtilities));
        this.config = config ?? throw new ArgumentNullException(nameof(config));

        if (environment.IsProduction() == false)
        {
            var mediaSettings = new MediaSettings();
            this.config.GetSection("Application").GetSection("Media").Bind(mediaSettings);

            var rootPath = Directory.GetParent(mediaSettings.RootPath).FullName;
            this.fileProvider = new PhysicalFileProvider(rootPath);
        }
        else
        {
            this.fileProvider = environment?.WebRootFileProvider ?? throw new ArgumentNullException(nameof(environment));
        }
    }

    public ProcessingBehavior ProcessingBehavior { get; } = ProcessingBehavior.CommandOnly;

    public Func<HttpContext, bool> Match { get; set; } = _ => true;

    public bool IsValidRequest(HttpContext context) => this.formatUtilities.GetExtensionFromUri(context.Request.GetDisplayUrl()) != null;

    public Task<IImageResolver> GetAsync(HttpContext context)
    {
        // Path has already been correctly parsed before here.
        IFileInfo fileInfo = this.fileProvider.GetFileInfo(context.Request.Path.Value);

        // Check to see if the file exists.
        if (fileInfo.Exists == false)
        {
            return Task.FromResult<IImageResolver>(null);
        }

        var metadata = new ImageMetadata(fileInfo.LastModified.UtcDateTime, fileInfo.Length);
        return Task.FromResult<IImageResolver>(new PhysicalFileSystemResolver(fileInfo, metadata));
    }
}
```

**Comment by shearer3000** [comment]
Hi @bergmania thanks for the code sample above. Just checking this definitely worked for you? When I updated our website to use it, the media section all works fine but the frontend continues to show the original image rather than the crop the url specifies (querystring). Its like Imagesharp still isn't handling the request and is still falling back to the static file provider. 

You mentioned:

> important thing is that the ImageSharpMiddleware are running before the StaticFileMiddleware

Is that regarding these lines of code?

```
                    app.UseImageSharp();
                    app.UseStaticFiles(new StaticFileOptions
                    {
                        FileProvider = fileProvider,
                        RequestPath = "/media"
                    });
```

any other thoughts or ideas why Imagesharp continues to ignore handling the image request would be so appreciated.

@creativesuspects i take it your code works for you now?

thanks
Andrew

**Comment by creativesuspects** [comment]
> @creativesuspects i take it your code works for you now?

Yes, it works. I’m actively using it on dev, staging and production for a project. Although I still need the NotificationHandler to make sure the physical files are being deleted on dev and staging. But again, this may be a Dropbox related issue. I’m not sure. Maybe you could use my code (without the NotificationHandler) on a UNC network path to see what happens?

Even with this code working and even if Umbraco would build something similar into the core to make it easier to change the media file location on a specific environment it still sucks that you can’t use a simple virtual directory on IIS. I often use additional virtual directories for other files that are being stored, like PDF invoices or reports. These files also need to be shared across dev and staging. Of course this is not an Umbraco issue, but a .NET Core issue. Luckily with these files I don’t have to worry about ImageSharp, so it can probably be fixed with just a few lines of code:

https://www.jauernig-it.de/asp-net-coreiis-serving-content-from-a-file-share/

**Comment by shearer3000** [comment]
yes my thoughts exactly! the amount of time I've spent trying to get this working is ridiculous (given that it took 2 seconds to create a virtual directory in .net 4) but the silver lining is that its been a good way of learning .net core. 

I hadn't been able to get your code working with a UNC path, but im about to try again now :)

**Comment by shearer3000** [comment]
hi @creativesuspects 
I managed to get the code sample working for me – thanks for providing it. 😁
The issue was that the value I was using for the “RootPath” variable in CustomMediaFileSystemProvider was the media folder path location, not the actual parent/root folder above it, so was getting a “file not found” on media files. I see you had 2 app settings for probably this reason too. I now realise that ImageSharp, given the root folder path, will work out the “/media” aspect of the file path using the PhysicalFileSystem that has been registered. I'm still learning netcore as I go I guess. As you say, it would be very helpful for a future version of Umbraco to have something in the core to make this easier to configure/change, and I'm still not entirely sure why 9 out of 10 people that have different environments in their umbraco 9 deployment lifecycle haven’t been asking for how to do something like this...
Thanks
Andrew

**Comment by AreYouSureYouKen** [comment]
I have recently started working on an Umbraco 9 project as well and have ran into this issue now. I have configured a custom virtual directory but ImageProcessor is not running for me either. I have used the code posted here with success and the ImageProcessor is using our virtual folder now. However this feels a little bit hacky and something that Umbraco could facilitate better as I imagine more people are running into this issue as well. 
It took me a while to find this specific post to find a working solution.

**Comment by creativesuspects** [comment]
@AreYouSureYouKen This issue has been fixed in version 9.3 which should be released pretty soon, so no more need for a custom FileSystemProvider. https://umbraco.com/blog/umbraco-93-release-candidate/

**Comment by AreYouSureYouKen** [comment]
@creativesuspects I updated to version 9.3 and tried using the new setting as shown in the release blog post. I however either get an error when I try to connect to a mapped network drive
`DirectoryNotFoundException: Could not find a part of the path 'S:\'.`
When I write a fully qualified network path, which I used for the solution before 9.3, it writes the images to wwwroot/[ipaddress]/[rest of folder structure]

**Comment by creativesuspects** [comment]
@AreYouSureYouKen I haven't tested the new feature myself, but I will do that tomorrow or early next week. Maybe you can find some helpful info in the PR: https://github.com/umbraco/Umbraco-CMS/pull/11783

**Comment by shearer3000** [comment]
the new umbraco 9.3 settings don't seem to work for me, i posted here https://github.com/umbraco/Umbraco-CMS/pull/11783#issuecomment-1035579709

**Comment by ronaldbarendse** [comment]
@shearer3000 The 9.3.1 patch release fixed the issue when setting `Umbraco:CMS:Global:UmbracoMediaPhysicalRootPath` to an UNC path (see PR https://github.com/umbraco/Umbraco-CMS/pull/11982), so this should now be fixed. Please let us know and close this issue if it now works for you!

**Comment by jacklawry** [comment]
I seem to have this (or a very similar issue) but in v10.

**Comment by kjac** [comment]
Hi everyone.

I've just tested storing media outside the default folder on V10.3.2 and it works just fine, both with absolute and relative paths.

This is the configuration:

![image](https://user-images.githubusercontent.com/7405322/212162449-8e0e7837-f781-4bd1-aa33-d82ea9b0f5b1.png)

Images are stored in `C:\Temp\media`:

![image](https://user-images.githubusercontent.com/7405322/212162596-fe139423-28cc-4ac3-8d84-05f6136c7533.png)

And resizing works as expected:

![image](https://user-images.githubusercontent.com/7405322/212162730-0046e992-3bad-46b1-a67f-fe73623b6db5.png)

As per [the docs](https://docs.umbraco.com/umbraco-cms/reference/configuration/globalsettings#umbraco-media-physical-root-path), absolute and relative paths are supported by `UmbracoMediaPhysicalRootPath`. UNC paths *should* be supported as well (see https://github.com/umbraco/Umbraco-CMS/pull/11982) but I can't verify that at this time. Worst case I assume the UNC path can be mapped to a drive and used by means of an absolute path?

Alternatively I highly recommend looking at the [Azure Blob Storage provider](https://docs.umbraco.com/umbraco-cms/extending/filesystemproviders/azure-blob-storage) as an alternative to [creating a completely custom provider](https://docs.umbraco.com/umbraco-cms/extending/filesystemproviders).

I'm going to go ahead and close this as the image resizing does indeed seem to work for media stored outside of the default media location. If anyone continues to experience issues based for V10.3.2+, please do not hesitate to reach out.
