### ISSUE TITLE
SQL Timeouts from TrackedReferencesRepository.GetPagedRelationsForItem

### ISSUE THREAD

**Issue by stevemegson** [umbraco/Umbraco-CMS#12190]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.1

### Bug summary

On a site with 12k rows in umbracoNode and 22k rows in umbracoRelation, I see SQL timeouts when the Info content app tries to load references to the current content or media.

### Specifics

The query generated in `TrackedReferencesRepository.GetPagedRelationsForItem` to retrieve `pagedResult.TotalItems` takes around 90 seconds to run. The issue appears to be this join to find both parent to child and bidirectional relations:
```
INNER JOIN [umbracoNode] [cn]
ON (([umbracoRelationType].[dual] = 0 AND ([r].[parentId] = [cn].[id]))
 OR ([umbracoRelationType].[dual] = 1 AND (([r].[childId] = [cn].[id]) OR ([r].[parentId] = [cn].[id]))))
```

After modifying the query to get just one type of relation at a time with the joins below, each runs in less than 1 second.
```
INNER JOIN [umbracoNode] [cn]
ON (([umbracoRelationType].[dual] = 0 AND ([r].[parentId] = [cn].[id])))
```
```
INNER JOIN [umbracoNode] [cn]
ON (([umbracoRelationType].[dual] = 1 AND (([r].[childId] = [cn].[id]) OR ([r].[parentId] = [cn].[id]))))
```

### An example stack trace

```
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
   at NPoco.Database.ExecuteScalar[T](String sql, CommandType commandType, Object[] args)
   at NPoco.Database.ExecuteScalar[T](Sql Sql)
   at NPoco.Database.ExecuteScalar[T](String sql, Object[] args)
   at NPoco.Database.PageImp[T,TRet](Int64 page, Int64 itemsPerPage, String sql, Object[] args, Func`3 executeQueryFunc)
   at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, String sql, Object[] args)
   at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, Sql sql)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.TrackedReferencesRepository.GetPagedRelationsForItem(Int32 id, Int64 pageIndex, Int32 pageSize, Boolean filterMustBeIsDependency, Int64& totalRecords)
   at Umbraco.Cms.Core.Services.Implement.TrackedReferencesService.GetPagedRelationsForItem(Int32 id, Int64 pageIndex, Int32 pageSize, Boolean filterMustBeIsDependency)
   at Umbraco.Cms.Web.BackOffice.Controllers.TrackedReferencesController.GetPagedReferences(Int32 id, Int32 pageNumber, Int32 pageSize, Boolean filterMustBeIsDependency)
   at lambda_method954(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

### Steps to reproduce

Open the Info content app on a site with a large number of nodes and relations.

---
_This item has been added to our backlog [AB#18647](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/18647)_

**Comment by bergmania** [comment]
Hi @stevemegson..

Thanks for reporting. Sounds like a `union` will be more effective..

Are you able to try out the runtime of this query on your dataset

```sql
SELECT DISTINCT * FROM
(
SELECT [cn].[id] as nodeId, [cn].[uniqueId] as nodeKey, [cn].[text] as nodeName, [cn].[nodeObjectType] as nodeObjectType, [ct].[icon] as contentTypeIcon, [ct].[alias] as contentTypeAlias, [ctn].[text] as contentTypeName, [umbracoRelationType].[alias] as relationTypeAlias, [umbracoRelationType].[name] as relationTypeName, [umbracoRelationType].[isDependency] as relationTypeIsDependency, [umbracoRelationType].[dual] as relationTypeIsBidirectional
FROM [umbracoRelation] [r]
INNER JOIN [umbracoRelationType] [umbracoRelationType]
ON ([r].[relType] = [umbracoRelationType].[id])
INNER JOIN [umbracoNode] [cn]
ON (([umbracoRelationType].[dual] = 0 AND ([r].[parentId] = [cn].[id])))
INNER JOIN [umbracoNode] [pn]
ON ((([pn].[id] = [r].[childId]) AND ([cn].[id] = [r].[parentId])) OR (([pn].[id] = [r].[parentId]) AND ([cn].[id] = [r].[childId])))
LEFT JOIN [umbracoContent] [c]
ON ([cn].[id] = [c].[nodeId])
LEFT JOIN [cmsContentType] [ct]
ON ([c].[contentTypeId] = [ct].[nodeId])
LEFT JOIN [umbracoNode] [ctn]
ON ([ct].[nodeId] = [ctn].[id])
WHERE ([pn].[id] = 1098)
UNION
SELECT [cn].[id] as nodeId, [cn].[uniqueId] as nodeKey, [cn].[text] as nodeName, [cn].[nodeObjectType] as nodeObjectType, [ct].[icon] as contentTypeIcon, [ct].[alias] as contentTypeAlias, [ctn].[text] as contentTypeName, [umbracoRelationType].[alias] as relationTypeAlias, [umbracoRelationType].[name] as relationTypeName, [umbracoRelationType].[isDependency] as relationTypeIsDependency, [umbracoRelationType].[dual] as relationTypeIsBidirectional
FROM [umbracoRelation] [r]
INNER JOIN [umbracoRelationType] [umbracoRelationType]
ON ([r].[relType] = [umbracoRelationType].[id])
INNER JOIN [umbracoNode] [cn]
ON (([umbracoRelationType].[dual] = 1 AND (([r].[childId] = [cn].[id]) OR ([r].[parentId] = [cn].[id]))))
INNER JOIN [umbracoNode] [pn]
ON ((([pn].[id] = [r].[childId]) AND ([cn].[id] = [r].[parentId])) OR (([pn].[id] = [r].[parentId]) AND ([cn].[id] = [r].[childId])))
LEFT JOIN [umbracoContent] [c]
ON ([cn].[id] = [c].[nodeId])
LEFT JOIN [cmsContentType] [ct]
ON ([c].[contentTypeId] = [ct].[nodeId])
LEFT JOIN [umbracoNode] [ctn]
ON ([ct].[nodeId] = [ctn].[id])
WHERE ([pn].[id] = 1098)
) u
ORDER BY (u.[relationTypeAlias])

Where `1098` should be replaced by on of your ids will lots of relations
```

**Comment by stevemegson** [comment]
Hi @bergmania,

That union is much quicker, under 1 second.

Comparing the query plans to see why the existing query is so slow, I've realised that it can't work out which relations are relevant and seems to end up doing a complete join of `umbracoRelation`, `umbracoRelationType` and `umbracoNode` before filtering for the few relevant rows. The query is just as slow for nodes which have no relations.

Although it should be redundant, adding an explicit where clause to the existing query seems to be enough to fix that, so it can consider only those relations which involve the current node. For my database this ends up being quicker than the union by a factor of 6.
```
WHERE ([pn].[id] = 1120)
AND ([r].childId = 1120 OR [r].parentId = 1120)
```

If I also add a new index `IX_umbracoRelation_childParentType` on `[childId] ASC, [parentId] ASC, [relType] ASC` then the query will use that as well as the existing `IX_umbracoRelation_parentChildType`, but with my database there's no noticeable change in performance - it's fast enough without the extra index.

**Comment by bergmania** [comment]
Thanks for the feedback @stevemegson .. We also investigated that additional index, but could also not see any performance gains.

If I make a PR with this extra where clause, will you be able to test out a nightly build before we ship it, to ensure it works as expected?

**Comment by stevemegson** [comment]
Yes, testing a nightly build would be no problem.

**Comment by bergmania** [comment]
Hey @stevemegson. Sorry for the delay. The nightly is available with the following version number: `9.5.0-preview20220331.88392`
More info about the nightlies here:
https://our.umbraco.com/documentation/Fundamentals/Setup/Install/installing-nightly-builds

**Comment by stevemegson** [comment]
@bergmania that looks good to me. The overall response time of `GetPagedReferences` is a few hundred milliseconds, so vastly improved and not really noticeable as the Info app loads.

**Comment by bergmania** [comment]
Hi @stevemegson..  
Thank you so much for the help. That has been extremely helpful 💪

**Comment by thomashdk** [comment]
Hi

I'm running version 9.4.3 and are still getting this error.
Can see there was a fix 9.4.2.

When I try to delete a node I'm getting this error:

`at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
   at NPoco.Database.ExecuteScalar[T](String sql, CommandType commandType, Object[] args)
   at NPoco.Database.ExecuteScalar[T](Sql Sql)
   at NPoco.Database.ExecuteScalar[T](String sql, Object[] args)
   at NPoco.Database.PageImp[T,TRet](Int64 page, Int64 itemsPerPage, String sql, Object[] args, Func`3 executeQueryFunc)
   at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, String sql, Object[] args)
   at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, Sql sql)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.TrackedReferencesRepository.GetPagedDescendantsInReferences(Int32 parentId, Int64 pageIndex, Int32 pageSize, Boolean filterMustBeIsDependency, Int64& totalRecords)
   at Umbraco.Cms.Core.Services.Implement.TrackedReferencesService.GetPagedDescendantsInReferences(Int32 parentId, Int64 pageIndex, Int32 pageSize, Boolean filterMustBeIsDependency)
   at Umbraco.Cms.Web.BackOffice.Controllers.TrackedReferencesController.GetPagedDescendantsInReferences(Int32 parentId, Int32 pageNumber, Int32 pageSize, Boolean filterMustBeIsDependency)
   at lambda_method1200(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

**Comment by bergmania** [comment]
Hi @thomashdk ..

Can you give some more info. E.g the system info from the help panel?

Do you know how many content and media nodes you have, and what type do you try to delete? It is a root or anything.. Overall I would like context, so I maybe can reproduce :)

**Comment by beliskner** [comment]
To add some context, for the GetPagedDescendantsInReferences call while removing publishedcontent our development environment has around 17k nodes. The production environment quite a bit more.

The GetPagedItemsWithRelations that is used for deleting media calls upon ~30k media items.

We've fixed the GetPagedDescendantsInReferences query by adding the following two lines to the end query builder (the first declaration var sql = in the function):
                .Where<NodeDto>(x => x.NodeId == parentId, "pn")
                .Where<RelationDto>(x => x.ChildId == parentId || x.ParentId == parentId, "r");

And the GetPagedItemsWithRelations fix was to add the following chain to change:
`            if (ids.Any())
            {
                sql = sql.Where<NodeDto>(x => ids.Contains(x.NodeId), "pn");
            }
`

to:

`            if (ids.Any())
            {
                sql = sql.Where<NodeDto>(x => ids.Contains(x.NodeId), "pn").Where<RelationDto>(x => ids.Contains(x.ChildId) || ids.Contains(x.ParentId), "r");
            }
`

**Comment by thomashdk** [comment]
Hi

I just updated to 9.5.0 and hopped that would fix it, but as @beliskner wrote it did not fix it.

When trying do delete a node after some time it timesout and gives this error:

  `at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
     at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
     at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
     at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
     at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
     at System.Data.SqlClient.SqlDataReader.get_MetaData()
     at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
     at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
     at System.Data.SqlClient.SqlCommand.ExecuteScalar()
     at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
     at NPoco.Database.ExecuteScalarHelper(DbCommand cmd)
     at NPoco.Database.ExecuteScalar[T](String sql, CommandType commandType, Object[] args)
     at NPoco.Database.ExecuteScalar[T](Sql Sql)
     at NPoco.Database.ExecuteScalar[T](String sql, Object[] args)
     at NPoco.Database.PageImp[T,TRet](Int64 page, Int64 itemsPerPage, String sql, Object[] args, Func`3 executeQueryFunc)
     at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, String sql, Object[] args)
     at NPoco.Database.Page[T](Int64 page, Int64 itemsPerPage, Sql sql)
     at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.TrackedReferencesRepository.GetPagedDescendantsInReferences(Int32 parentId, Int64 pageIndex, Int32 pageSize, Boolean filterMustBeIsDependency, Int64& totalRecords)
     at Umbraco.Cms.Core.Services.Implement.TrackedReferencesService.GetPagedDescendantsInReferences(Int32 parentId, Int64 pageIndex, Int32 pageSize, Boolean filterMustBeIsDependency)
     at Umbraco.Cms.Web.BackOffice.Controllers.TrackedReferencesController.GetPagedDescendantsInReferences(Int32 parentId, Int32 pageNumber, Int32 pageSize, Boolean filterMustBeIsDependency)
     at lambda_method2059(Closure , Object , Object[] )
     at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
  --- End of stack trace from previous location ---
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
  --- End of stack trace from previous location ---
     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`
     
     
     @beliskner  do you have a work around I can inplement for now ??

**Comment by thomashdk** [comment]
Also getting this in the console.
`"errorMsg":"Failed to retrieve usages for descendants of parent with id 83385","data":{"ExceptionMessage":"Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding."`

![image](https://user-images.githubusercontent.com/6445636/169819564-16cabea7-ba04-4db6-8088-716b09c782f7.png)

**Comment by beliskner** [comment]
Hi @thomashdk,

Let me just stipulate before sharing our workaround that @patrickdemooij9 has pointed out that the query produced through our workaround does **NOT** produce the desired outcome of the repository. It does however at least allow BackOffice users to remove documents and media whilst this query is unoptimized. So if you decide to use this workaround make sure that you remove it as soon as it's fixed in the Umbraco framework.

Add this class to your solution: https://gist.github.com/beliskner/86f8dd0ac77119129479d529b243786d

Afterwards include this in your composers:
`// TODO: When this issue is resolved in Umbraco stop hijacking the repository and remove this composer + class
builder.Services.AddUnique<ITrackedReferencesRepository, HijackedTrackedReferencesRepository>();`

**Comment by thomashdk** [comment]
> Hi @thomashdk,
> 
> Let me just stipulate before sharing our workaround that @patrickdemooij9 has pointed out that the query produced through our workaround does **NOT** produce the desired outcome of the repository. It does however at least allow BackOffice users to remove documents and media whilst this query is unoptimized. So if you decide to use this workaround make sure that you remove it as soon as it's fixed in the Umbraco framework.
> 
> Add this class to your solution: https://gist.github.com/beliskner/86f8dd0ac77119129479d529b243786d
> 
> Afterwards include this in your composers: `// TODO: When this issue is resolved in Umbraco stop hijacking the repository and remove this composer + class builder.Services.AddUnique<ITrackedReferencesRepository, HijackedTrackedReferencesRepository>();`

Noted. Thanks for sharing! :)
