### ISSUE TITLE
[v10] ConfigurationEditor`T moved to Umbraco.Core.dll with no deprication period

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#12457]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10-RC

### Bug summary

In Umbraco v9 the `ConfigurationEditor` class existed in `Umbraco.Infrastructure.dll` however this has now moved to `Umbraco.Core.dll`

### Specifics

This issue is that this is a breaking change with no deprication period. It looks like it was planned as part of this merged issue https://github.com/umbraco/Umbraco-CMS/pull/9421 but I can't find any public notice that this was moving.

### Steps to reproduce

n/a

### Expected result / actual result

Much the same as the `ICoreScopeProvider` I'd expect some kind of way to migrate to the new API with some way of being notified of the move.

**Comment by Zeegaan** [comment]
Hey @mattbrailsford, I'm trying to test this out and i can't get it to break :/ could you tell me if I'm doing anything wrong here? 🙈 
- installed the 9.5 template with `dotnet new -i Umbraco.Templates`
- Created a umbraco package project with `dotnet new umbracopackage -n UmbracoPack`
- Created a custom configuration editor like so:
```
public class TestEditor : ConfigurationEditor
  {
      public string Title { get; set; }
  }
```
- Created a ConfigurationEditor<TestEditor> like so:
```
public class TestClass : ConfigurationEditor<TestEditor>
{
    public TestClass(IIOHelper ioHelper) : base(ioHelper)
    {
        
    }
    
    public string Test { get; set; }
}
```
- Packaged up the project with `dotnet pack`
- Created a 9.5 umbraco project with `dotnet new umbraco -n TestProj`
- Created a service using the editor as a property
```
public class TestService
{
    public TestClass TestEditor { get; set; } = new TestClass(null);
}
```
- Registered the new  
- Created a document type and edited the template like so:
```
@inject TestService _service
@{
	_service.TestEditor.Test = "Display test property";
	Layout = null;
}

<p>@_service.TestEditor.Test</p>
```
- I then upgraded my project to the new 10.0.0-rc3 and it still worked

**Comment by mattbrailsford** [comment]
So this is the exception I'm getting

````
An error occurred while starting the application.
TypeLoadException: Could not load type 'Umbraco.Cms.Core.PropertyEditors.ConfigurationEditor`1' from assembly 'Umbraco.Infrastructure, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.
Unknown location

ReflectionTypeLoadException: Could not load all types from "Vendr.Umbraco, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Cms.Core.PropertyEditors.ConfigurationEditor`1: Could not load type 'Umbraco.Cms.Core.PropertyEditors.ConfigurationEditor`1' from assembly 'Umbraco.Infrastructure, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.

Could not load type 'Umbraco.Cms.Core.PropertyEditors.ConfigurationEditor`1' from assembly 'Umbraco.Infrastructure, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.
Umbraco.Cms.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)

Loader Exceptions:
Could not load type 'Umbraco.Cms.Core.PropertyEditors.ConfigurationEditor`1' from assembly 'Umbraco.Infrastructure, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.
TypeLoadException: Could not load type 'Umbraco.Cms.Core.PropertyEditors.ConfigurationEditor`1' from assembly 'Umbraco.Infrastructure, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.

Show raw exception details
ReflectionTypeLoadException: Could not load all types from "Vendr.Umbraco, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping: . System.TypeLoadException on Umbraco.Cms.Core.PropertyEditors.ConfigurationEditor`1: Could not load type 'Umbraco.Cms.Core.PropertyEditors.ConfigurationEditor`1' from assembly 'Umbraco.Infrastructure, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'. Could not load type 'Umbraco.Cms.Core.PropertyEditors.ConfigurationEditor`1' from assembly 'Umbraco.Infrastructure, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null'.
Umbraco.Cms.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
Umbraco.Cms.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable<Assembly> assemblies, bool onlyConcreteClasses, Func<Type, bool> additionalFilter)
Umbraco.Cms.Core.Composing.TypeFinder.FindClassesOfType(Type assignTypeFrom, IEnumerable<Assembly> assemblies, bool onlyConcreteClasses)
Umbraco.Extensions.TypeFinderExtensions.FindClassesOfType<T>(ITypeFinder typeFinder, IEnumerable<Assembly> assemblies, bool onlyConcreteClasses)
Umbraco.Cms.Core.Composing.TypeLoader+<>c__DisplayClass21_0<T>.<GetTypes>b__0()
Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func<IEnumerable<Type>> finder, string action, bool cache)
Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func<IEnumerable<Type>> finder, string action, bool cache)
Umbraco.Cms.Core.Composing.TypeLoader.GetTypes<T>(bool cache, IEnumerable<Assembly> specificAssemblies)
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
UmbracoV10_VendrV2.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
+
            services.AddUmbraco(_env, _config)
System.RuntimeMethodHandle.InvokeMethod(object target, ref Span<object> arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(object instance, IServiceCollection services)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder+<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(object instance, IServiceCollection services)
Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder+<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, object instance)
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder+<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
Microsoft.Extensions.Hosting.HostBuilder.Build()
Umbraco.Cms.Web.Common.Hosting.UmbracoHostBuilderDecorator.Build()
UmbracoV10_VendrV2.Program.Main(string[] args) in Program.cs
+
            => CreateHostBuilder(args)

Show raw exception details
.NET 6.0.5 X64 v6.0.0.0    |   Microsoft.AspNetCore.Hosting version 6.0.5+e5f183b656a0e8bc087108130a5a9b54ae94494e    |    Microsoft Windows 10.0.22000    |   [Need help?](http://go.microsoft.com/fwlink/?LinkId=517394)
````

So I think the problem manifests itself if you implement a `DataEditor` that uses your config editor as these would get automatically resolved by Umbraco and it's in that resolution process this error is being thrown.

Maybe implement a data editor like the following

````csharp
[DataEditor("test", "Test")]
public class TestEditor : DataEditor
{
    public TestEditor(IDataValueEditorFactory dataValueEditorFactory, EditorType type = EditorType.PropertyValue) 
        : base(dataValueEditorFactory, type)
    { }

    protected override IConfigurationEditor CreateConfigurationEditor()
        => new TestClass(null);
}
````

Then I think Umbraco should attempt to resolve it on Startup

**Comment by Zeegaan** [comment]
@mattbrailsford  I've tried implementing your DataEditor but now the ConfiugrationEditor Complains 🙈 
![image](https://user-images.githubusercontent.com/70372949/169990975-3211a68c-b19d-46fd-b669-47f4ec7b71c2.png)

**Comment by mattbrailsford** [comment]
I believe your `TestEditor` class shouldn't extend `ConfigurationEditor`. It should just be a plain Poco class

**Comment by mattbrailsford** [comment]
Maybe try this

````csharp
public class TestConfig
{
    public string Title { get; set; }
}

public class TestConfigEditor : ConfigurationEditor<TestConfig>
{
    public TestClass(IIOHelper ioHelper) 
        : base(ioHelper)
    { }
    
    public string Test { get; set; }
}

[DataEditor("test", "Test")]
public class TestDataEditor : DataEditor
{
    public TestDataEditor(IDataValueEditorFactory dataValueEditorFactory, EditorType type = EditorType.PropertyValue) 
        : base(dataValueEditorFactory, type)
    { }

    protected override IConfigurationEditor CreateConfigurationEditor()
        => new TestConfigEditor(null);
}
````

**Comment by Zeegaan** [comment]
Thanks, still can't seem to break my package though 🤔 

Here i'm just trying to display the alias and it works just fine:
![image](https://user-images.githubusercontent.com/70372949/169994696-4f516994-12ad-4cfd-b6c9-ef9fb49160ed.png)
![image](https://user-images.githubusercontent.com/70372949/169994743-bbb60117-e5ac-41c4-b8a9-467058e46b9e.png)
![image](https://user-images.githubusercontent.com/70372949/169994787-e965a246-14df-4588-bd86-83075e093be3.png)

**Comment by Zeegaan** [comment]
Ah i can now reproduce! Thx for the help @mattbrailsford

**Comment by Zeegaan** [comment]
This should now be fixed in https://github.com/umbraco/Umbraco-CMS/pull/12467, thanks for reporting this! 🐛
