### ISSUE TITLE
Umbraco allows usernames with spaces but doesnt allow change password for this users

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#14808]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

So I had little digging, when UsernameIsEmail is set to false, umbraco allows to set username to anything, including namespaces!
so there are 2 different issues around it:
1) Umbraco is not using UserValidator when saving users, which allows to create user with spaces even when UserOptions.AllowedUserNameCharacters does not allows spaces!
2) When using AllowedUserNameCharacters in settings for umbraco security it applies only to members, not backoffice users!

### Steps to reproduce

subbug 1:
1) set UsernameIsEmail to false
2) create user with namespace in login
3) try to change password / unlock / disable user
4) you will get notication about username is incorrect
subbug 2:
1) set UsernameIsEmail to false
2) set AllowedUserNameCharacters to include space
3) create user with namespace in login
4) try to change password / unlock / disable user
5) you will get notication about username is incorrect

### Expected result / actual result

User will be validated with same user validator on save.
It will be possible to override allowed characters for users in backoffice.

**Comment by Zeegaan** [comment]
@bielu How are you allowing space in usernames, I have my `AllowedUserNameCharacters` set like: 
```
        "AllowedUserNameCharacters": "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+\\ "
```

**Comment by Zeegaan** [comment]
Also, could I ask that you create an entire seperate issue for `subbug 1`, this way we can track both seperately, and close this when your PR gets merged 😁

**Comment by Zeegaan** [comment]
I cannot create a User with a space in the Username, but I can change it and then save it 🤔
So I'm not sure why you're allowed to 😅 
![CantCreateUserWithSpaceInName](https://github.com/umbraco/Umbraco-CMS/assets/70372949/7ace141b-1fc5-4f42-b99e-226d7a47d629)

**Comment by Zeegaan** [comment]
So just to conclude: I cannot reproduce sub-bug 1, this should be its own issue (Not sure it is an issue, as it works as intended on my end)
But I can reproduce sub-bug 2 and will take a look at the PR (looks like it fixes the issue), how does that sound for you @bielu  😁

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14810

**Comment by Zeegaan** [comment]
And yes some funky behavior will occur if you migrate users with spaces, but doesn't have them allowed. Will talk to the team on how to go about handling such a case 😁

**Comment by bielu** [comment]
@Zeegaan can you confirm in which v10 patch version it will be release + approx date? :)

**Comment by jerpenol** [comment]
@Zeegaan any idea when this will be included in a release? I am still encountering #14823 in 13.2.2
