### ISSUE TITLE
Tinymce not sticky in classic mode in Umbraco 13.2

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#14911]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.5.0

### Bug summary

Richtext editor are not sticky in classic mode - so the toolbar disapear when make longe text in the richtext editor

### Steps to reproduce

Use the richtext editor - 

- set the mode to classic on the datatype.
- try the rich editor and paste a large text

Addingthis to the config are not working or doing anything.

`"RichTextEditor": {
        "CustomConfig": {
          "toolbar_sticky": true
        }
}`

### Expected result / actual result

Like in Umbraco 8 (maybe 9) let the toolbar scroll down when writing a lon text.

Umbraco 11

start
<img width="493" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/6445636/dcc06c05-9cc7-40e8-9562-0fd80a4c3540">

Scrolled down
<img width="466" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/6445636/361ccc61-02f0-4bf3-9605-07f8bd5e9e1f">

Umbraco 8

start
<img width="425" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/6445636/515841d0-b8db-4c5f-a3e4-4ef416c9016e">

Scrolled down

<img width="460" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/6445636/0d7b09aa-012b-42df-9874-38b96f8f9370">

Adding this sould maybe make it work:

`"RichTextEditor": {
        "CustomConfig": {
          "toolbar_sticky": true
        }
}`

---
_This item has been added to our backlog AB#33388_

**Comment by netcamo** [comment]
Hi @thomashdk I hope everything is going well for you!

Thank you for reporting the issue! I have been able to reproduce it and  checked that it worked as you expected on version v10.7.0 
This looks like a regression bug and we will try to pick it up as soon as possible.

Have a wonderful day! 😄

**Comment by netcamo** [comment]
After more investigation I have found out that this issue first occurs at v11.0.0

**Comment by alandraper** [comment]
Has there been any progress on this? I just watched my client struggle to get the toolbar to appear at all, making her job impossibly difficult. 

There's an empty space where the toolbar should be. 
<img width="748" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/13674761/2eb6cf45-108e-45fb-9d88-242af9851ab4">


I've found that selecting all the content, cutting it, and pasting it back into the rich text area causes the toolbar to reappear. 
<div data-alloy-vertical-dir="toptobottom" tabindex="-1" class="tox-editor-header tox-editor-dock-fadeout">grid
Looking at the developer tools, I see this element
`<div data-alloy-vertical-dir="toptobottom" tabindex="-1" class="tox-editor-header tox-editor-dock-fadeout">`

If I manually delete the class "tox-editor-dock-fadeout" then the toolbar reappears. 

<img width="441" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/13674761/72d1eaed-93ac-4452-9963-693de98ee4f7">

**Comment by alandraper** [comment]
I have a hack to get the toolbar to appear, at least in Chrome. 

1. Add a bookmark to your Bookmarks Bar. It doesn't matter to what page because we'll edit it. 
2. Right-click on the new bookmark and choose "Edit..."
3. Change the title to "Show Umbraco Rich Text Toolbars"
4. Change the URL to the following
`javascript:document.querySelectorAll(".tox-editor-dock-fadeout").forEach(function (el){el.classList.remove("tox-editor-dock-fadeout")})`
5. Click Save

Now, when on an Umbraco Page, just click the button and all the toolbars appear.

**Comment by iOvergaard** [comment]
Hi @alandraper 

I am looking into issues with tinymce in Umbraco 13 (same tinymce version as Umbraco 11 used). Although your first screenshots indicated you were having trouble with all rich text editors, your screenshots in your latest comment seems to show a grid, which leads me to believe you are experiencing the same problem as described in #15515. The problem with the grid layout seems to be happening whenever the option `toolbar_sticky` is turned on, which it is by default for all grid layout rich text editors. Contrary to your initial issue description, setting this option in appsettings to `false` should solve it for rich text editors inside a grid layout.

I wonder if you have tried this out in the latest Umbraco 13.1 and could report on which of the issues persist?

**Comment by sean-p-m** [comment]
> Hi @alandraper
> 
> I am looking into issues with tinymce in Umbraco 13 (same tinymce version as Umbraco 11 used). Although your first screenshots indicated you were having trouble with all rich text editors, your screenshots in your latest comment seems to show a grid, which leads me to believe you are experiencing the same problem as described in #15515. The problem with the grid layout seems to be happening whenever the option `toolbar_sticky` is turned on, which it is by default for all grid layout rich text editors. Contrary to your initial issue description, setting this option in appsettings to `false` should solve it for rich text editors inside a grid layout.
> 
> I wonder if you have tried this out in the latest Umbraco 13.1 and could report on which of the issues persist?

I am having the same issue (toolbar missing from rich text editors inside a grid layout). I have installed Umbraco 13.1 RC and can confirm the problem still exists :-(

**Comment by iOvergaard** [comment]
@sean-p-m Great to hear (not about your experience, of course). I believe we have isolated the fix and there is now a pending pull request for #15515 which describes the problem you are experiencing.

**Comment by alandraper** [comment]
Yes, it so sounds the same as 15515. I can try the config change on their site.  I can't upgrade their site to 13 though. They are my one client who still has DocTypeGridEditor and I think there was a conflict that wouldn't let me upgrade.

**Comment by iOvergaard** [comment]
@alandraper the proposed workaround should work on Umbraco 11 as well, so please go ahead and try that. Would also be interested to know what kind of conflict you ran into. I know the author of DocTypeGridEditor stopped supporting it, but .NET wise it should be able to run on newer Umbracos. Umbraco 11 reached its end-of-life last year.

**Comment by iOvergaard** [comment]
This should be fixed with #15595 which we expect to release with Umbraco 13.2. Thanks for reporting this! #h5yr

**Comment by thomashdk** [comment]
Stille a issue in 13.2.0

**Comment by iOvergaard** [comment]
Hi @thomashdk 

Thanks for reporting back in. We will re-verify the bug report and see what's up!

**Comment by thomashdk** [comment]
> Hi @thomashdk
> 
> Thanks for reporting back in. We will re-verify the bug report and see what's up!

Sounds good, thanks.

We have a lot of frustrated clients..  :D

**Comment by iOvergaard** [comment]
I can confirm that this is still an issue, at least with the `sticky_toolbar` option. Back before V11 when we still used TinyMCE v4, we had some custom code to make the toolbar sticky. This code didn't work with TinyMCE v6, which we now use, and Tiny had since implemented their `sticky_toolbar` option. However, I simply cannot make it work with the current layout we have in the backoffice.

Interestingly enough setting `inline: true` on TinyMCE seems to give the same experience as a sticky toolbar of sorts, and although it doesn't position the toolbar correctly in my opinion, it is still visible within the viewport wherever you are:

Here appearing beneath the editor:
![image](https://github.com/umbraco/Umbraco-CMS/assets/752371/aef9bc0e-0569-4369-9b2f-df3a0cd9d1ea)

And here appearing at the top of the page when I am scrolled into the middle of an RTE:
![image](https://github.com/umbraco/Umbraco-CMS/assets/752371/2997f9e8-cd3d-4922-af0a-a293418a9b9b)

We will have to investigate this further as it seems there is something up with the styling since the default TinyMCE configuration `toolbar_sticky` doesn't seem to work at all - in fact it hides the toolbar entirely.

**Comment by chriskarkowsky** [comment]
> Has there been any progress on this? I just watched my client struggle to get the toolbar to appear at all, making her job impossibly difficult.
> 
> There's an empty space where the toolbar should be. <img alt="image" width="748" src="https://private-user-images.githubusercontent.com/13674761/291099488-2eb6cf45-108e-45fb-9d88-242af9851ab4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MzAsIm5iZiI6MTcxMjY5MjQzMCwicGF0aCI6Ii8xMzY3NDc2MS8yOTEwOTk0ODgtMmViNmNmNDUtMTA4ZS00NWZiLTlkODgtMjQyYWY5ODUxYWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5YjJlNWEzZDgxYzAxNWEyYWQwMGE1MjcyYjMzYjYzMDZiYTY5YjViOTZhN2E5OTc2ZTJhYmVmZmU2MDBkNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.45IgWadJV93_rrV8oUTJjUsSR6-vGiDW44zF7H4XhNA">
> 
> I've found that selecting all the content, cutting it, and pasting it back into the rich text area causes the toolbar to reappear.
> 
> grid Looking at the developer tools, I see this element `
> `
> If I manually delete the class "tox-editor-dock-fadeout" then the toolbar reappears.
> 
> <img alt="image" width="441" src="https://private-user-images.githubusercontent.com/13674761/291100976-72d1eaed-93ac-4452-9963-693de98ee4f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MzAsIm5iZiI6MTcxMjY5MjQzMCwicGF0aCI6Ii8xMzY3NDc2MS8yOTExMDA5NzYtNzJkMWVhZWQtOTNhYy00NDUyLTk5NjMtNjkzZGU5OGVlNGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZDIwYjRkNGE0OTAwMzM3MTRmOWExOThmODQ3NjE4OWU0NWJlZDAzNzAxZWRhMzY5Y2M3YjJjNDMyZWM0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BLGQYfJl0M20kHm2vPnJTmaT5WP28704P516OmTOfVQ">

I have this exact same issue in 12.2.

**Comment by mikeranscombe** [comment]
Is this issue being addressed? We've just upgraded from v10 to v13.3.1 and this issue is still occuring on the vanilla RTE; the toolbar  won't stay at the top of the RTE viewport but moves off when is is scrolled.

We've implement a CSS/config workaround that allows for a "floating" toolbar but that is just annoying to our content managers, as it gets in the way when editing content and is a bit flakey - it can disappear whilst editing.

**Comment by asawyermarathon** [comment]
This is also a serious issue for us in 13.3.2. I've found the best workaround is to set a static RTE height, 630 seems right on a 1080p screen.

I've tried enabling toolbar sticky:

`"RichTextEditor": {
  "CustomConfig": {
    "toolbar_sticky": "true" //buggy, not applying until height changes
  }
},`

this, coupled with custom css:

`ng-form[name="infiniteEditorForm"] .tox-editor-header {
    max-width: 800px !important;
    position: fixed !important;
    border: 1px solid #d8d7d9 !important;
    margin-left: -1px !important;
    margin-top: -1px !important;
}
ng-form[name="infiniteEditorForm"] .tox-sidebar-wrap {
    margin-top: 87px !important;
}`

This almost works, but unfortunately, the height is not properly computed until the RTE height changes. This means the toolbar isn't sticky until an editor enters text that changes the RTE height. 

My guess is that the tinymce initialization event is not calculating the RTE with the sticky rule.

**Comment by oscar-zm** [comment]
To add onto asawyermarathon; I'm also experiencing this issue on Umbraco 13.3.1. The toolbar in the Rich Text Editor is not sticky, which makes editing longer texts quite cumbersome as I have to scroll back up frequently to access the toolbar.

Has there been any progress on resolving this issue, or are there any official workarounds or updates available? Your help and any insights would be greatly appreciated!

**Comment by wadrschall** [comment]
I can confirm in v 13.3.2, we are not seeing the behavior of the tinymce richtext editor changing to "sticky" menus. Is there an ETA on when this will be addressed? A previous comment indicated it was fixed in 13.2, but that does not appear to be the case unless there are additional settings we need to set that we are unaware of.

**Comment by jcrittenden** [comment]
Still an issue in 13.3.0.

**Comment by iOvergaard** [comment]
Hi everyone,
To summarise what I have understood from the conversation: The issue seems to arise because the editor does not have a fixed height by default in Umbraco, which creates a race condition where TinyMCE cannot calculate where to place the sticky toolbar.

As stated before, we used to override the CSS in the older version of TinyMCE to make this work as it was not a native feature. It has since become a native feature in TinyMce 6, but it has never worked properly in Umbraco.

We'd be happy to take this up again and give it another stab, but I am not sure whether we can solve this without workarounds seeing, that it would probably require some kind of fixed height, which would cause trouble for the Auto Height feature we also need to support. I am wondering if some of it could be toggleable to let users decide on the behavior they want.

I will make sure this gets included in a development sprint.

**Comment by leekelleher** [comment]
Follow up on this, I'd been investigating if we can support `toolbar_sticky` with the "autoresize" (auto-height) feature, but so far, my attempts have been unsuccessful. 😖

**Comment by mcl-sz** [comment]
We've created a TinyMCE plugin to bring back this functionality for our Umbraco 13 sites:

https://gist.github.com/mcl-sz/87529b4914c601ac8b61a726fe6ce803

**Comment by thomashdk** [comment]
Sweet! Will giv it a try

**Comment by thomashdk** [comment]
> We've created a TinyMCE plugin to bring back this functionality for our Umbraco 13 sites:
> 
> https://gist.github.com/mcl-sz/87529b4914c601ac8b61a726fe6ce803

Works ! Thank you

**Comment by ewilkinson-marathon** [comment]
I know this was closed, but just wanted to mention that this is still an issue in v13 (and also in the ProWorks v17+ Umbraco.TinyMCE package). The provided gist mentioned here is a good start but it does have some flaws, there's a typo where it's not setting "px" after the padding-top in the CSS as you begin to scroll - resulting in a bounce. And, it doesn't currently consider the height of the Tabs panel above the properties - overlapping that section rather than staying below it.

**Comment by mcl-sz** [comment]
@ewilkinson-marathon, I just added support for tabs and added px for the padding-top, would you like to try again?

**Comment by ewilkinson-marathon** [comment]
> [@ewilkinson-marathon](https://github.com/ewilkinson-marathon), I just added support for tabs and added px for the padding-top, would you like to try again?

gist plugin updates look good.
