### ISSUE TITLE
multi-language CMS: misleading/redundant links

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#17586]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

any version of Umbraco 13, but using 13.5.2 at time of writing

### Bug summary

Given a traditional multi language/site setup in Umbraco e.g. English, German and French languages with a content tree for each, The links section of a page will show a link for all of the languages when only 1 is relevant/applicable (i.e. 1 language selected in Culture and hostnames section), and will show a "This document is published but is not in the cache" for all others.

![image](https://github.com/user-attachments/assets/faa01ab2-60ab-4637-a874-41a8450bf4ec)

### Steps to reproduce

1. add multiple languages to CMS settings:
![image](https://github.com/user-attachments/assets/de129541-7bcb-4bfe-8657-a61a577f7cf7)

2. add content tree per language and select
![image](https://github.com/user-attachments/assets/3c1eaf4f-9823-40a6-b18f-fc0e7f9dec77)
![image](https://github.com/user-attachments/assets/f2c310ec-300f-4164-85cc-a004e1cd22fb)
![image](https://github.com/user-attachments/assets/1b0b3de6-df09-4e98-9a7b-f25692b2a2cb)

3. observe Links section on content node
![image](https://github.com/user-attachments/assets/e53c0777-c7f9-43dd-909d-e20c34c2e0b0)

NB "allow vary by culture" not selected on doctypes - this isn't a language variants CMS setup.

### Expected result / actual result

Expected: only link relevant to language (culture) are shown on content node 

Actual: shows a link per language defined in CMS irrespective of culture settings on specific content tree

**Comment by Dark0d3** [comment]
@shearer3000 

**This is not a bug**

In Umbraco, the root node is treated as the default route for all configured languages unless you explicitly set up specific Culture and Hostnames. This means the CMS will associate all defined languages (e.g., English, German, French) with the root node until a distinct hostname is specified for each.

![image](https://github.com/user-attachments/assets/d81e13dd-ba4c-4502-9b1a-22d09e7b761c)

Hope that make sense.

**Comment by enkelmedia** [comment]
Great @shearer3000, I'm not sure that @Dark0d3 got your point to be honest. 

I agree that this should be fixed - it's confusing for editors. Most of the development in Umbraco over the last years has been targeted towards 1:1 translation scenarios or using language variant nodes, but it's very common with the approach that you're showing here - especially with sites that have been upgraded from earlier versions.

**Comment by Dark0d3** [comment]
@enkelmedia I see your point, but I believe the transition away from node-based multivariant setups was made to simplify things for editors. I used to do the same up to v7. It was quite a complex system to manage, especially for sites that had to support multiple languages or adding a new variant. That said, I understand that sites upgraded from earlier versions may still face challenges.

**Comment by enkelmedia** [comment]
@Dark0d3 yep, I believe so as well. However, I'm not 100% convinced that this is the way to go for all kinds of scenarios. Sometimes the 1:1 setup just makes it more complicated for the editors. It really depends on the situation and I would argue that there is really no "right or wrong" here.

In the case of upgrading it really not a feasible option to "merge" nodes into variants. We have several clients where we will have to maintain a number of websites with the "old" setup for language nodes.

**Comment by shearer3000** [comment]
@Dark0d3 
I had tried with and without specific domain + language bindings but it was the same end result so i hadn't mentioned above. 

When i add the relevant domain and language bindings to my 3x top level nodes, for example:

![image](https://github.com/user-attachments/assets/944a43b6-9b43-4661-935e-5fd4274a333b)

i get the following in the Links section:
![image](https://github.com/user-attachments/assets/d72157d2-4b86-4372-9781-6a97c5216210)

whether this is a bug or not (i'd suggest it is), everyone would agree thats its not a great experience for content editors

**Comment by shearer3000** [comment]
@enkelmedia

> In the case of upgrading it really not a feasible option to "merge" nodes into variants. We have several clients where we will have to maintain a number of websites with the "old" setup for language nodes.

Yes that's the situation here - an "older" preexisting CMS set up using the traditional/conventional content tree. Like you say, 1:1 language variants isn't always the right fit anyway (and definitely not a feasible option to now "merge" nodes into variants). 

It feels like Umbraco is mixing up the two modes.

**Comment by Dark0d3** [comment]
> i get the following in the Links section: ![image](https://private-user-images.githubusercontent.com/2433680/388342387-d72157d2-4b86-4372-9781-6a97c5216210.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNjI3NjAsIm5iZiI6MTczMjE2MjQ2MCwicGF0aCI6Ii8yNDMzNjgwLzM4ODM0MjM4Ny1kNzIxNTdkMi00Yjg2LTQzNzItOTc4MS02YTk3YzUyMTYyMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjFUMDQxNDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDYyOTc0NDkxYzU0YjA1OTZhZDgzYTRlOTkxYzNhZDdkMmVkMjRhMTZhMGQ0YWIxNGU2NWY1ODBkZTA1OTQ1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QcExfcirb5MVa1pXUwbNyYj-ve4eaksOYeGu2a_yLo4)
> 
> whether this is a bug or not (i'd suggest it is), everyone would agree thats its not a great experience for content editors

@shearer3000  In your case, you can just switch the culture variant, assign the desired hostname for that culture, and publish only the variant instead of the default one. This way, it won’t generate a URL for the default variant.

**Comment by nielslyngsoe** [comment]
This is fixed in newer versions of the CMS, only showing the relevant links in relation to your language scope or assigned hostnames; so I would advise upgrading to a later version.

Thanks for taking the time to report it in the first place — we do appreciate it, even when we can't get every issue over the finish line.
