### ISSUE TITLE
UI Bug – Encoded Characters Appear on "Add" Button in Group Picker (Hebrew UI)

### ISSUE THREAD

**Issue by LinnPower** [umbraco/Umbraco-CMS#19310]
### Which Umbraco version are you using?

15.4.1

### Bug summary

When using the Umbraco backoffice in  after migrating from 13 I encountered a UI rendering issue related to encoded characters.

🐞 Bug Description:
In the group picker area, the "Add" button displays unexpected encoded HTML entities (e.g., &#1511;&#1493;...) 

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/1e447cb7-bd43-4596-a916-012a76c772d6)
when using property editor block list and then you have a option to add to the list so in the button Add

**Comment by iOvergaard** [comment]
Thanks for the report. It looks like it is this bug #18166 resurfacing, which should have been fixed in 15.4.0 by #18960.

@LinnPower, could I ask you to copy/paste the System Information into this issue report, please? You can find it by clicking on the logo in the upper left corner and then clicking "System Information".

**Comment by LinnPower** [comment]
```
Umbraco system information
--------------------------------
Server OS: Ubuntu 24.10
Server Framework: .NET 9.0.0
Default Language: he
Umbraco Version: 15.4.1
Current Culture: en-US
Current UI Culture: en-US
Current Webserver: Kestrel
Models Builder Mode: Nothing
Runtime Mode: BackofficeDevelopment
Debug Mode: True
Database Provider: System.Data.SQLite
Current Server Role: Single
Umbraco build version: 15.4.1+0ad020f
Server time offset: 02:00:00
Runtime mode: BackofficeDevelopment
Browser (user agent): Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36
Browser language: en-US
Browser location:
http://localhost:63003/umbraco/section/content/workspace/document/edit/14918bc8-9e7d-4d10-b554-7b30c3fc33c3/invariant
User is admin: Yes
User sections: Umb.Section.Content, Umb.Section.Forms, Umb.Section.Media,
Umb.Section.Members, Umb.Section.Packages, Umb.Section.Settings,
Umb.Section.Translation, Umb.Section.Users
User culture: en-US
User languages: All
User document start nodes: None
```

**Comment by LinnPower** [comment]
just added the Umbraco system information

**Comment by leekelleher** [comment]
@LinnPower I'm not able to reproduce this on v15.4.1 or v16.0.0-rc.
Using the element type name "קבוצתקישורים" renders as expected, (not as HTML entity numbers).

I'm wondering if older files could be cached in your browser? Would you be able to either clear out your cache (e.g. <kbd>CTRL</kbd> + <kbd>F5</kbd>) or try testing on a different browser? Thank you.

**Comment by LinnPower** [comment]
Hi,
I tried both things you suggested and I still have the same
problem mentioned.

if there is any other ideas I'd love to hear from you

Thanks

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/strange-string-added-to-add-button/2262/10

**Comment by iOvergaard** [comment]
Hi there,
We're closing this issue as the affected version has since gone out of support — you can see which versions are currently supported in our [support policy](https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/).

That doesn't necessarily mean the problem is gone, but a lot has changed in the codebase since this was reported, and we're no longer shipping fixes for this version. If you're still seeing this on a currently supported version, please open a new issue referencing this one with updated reproduction steps, and we'll happily take a look.

Thanks for taking the time to report it in the first place — we do appreciate it, even when we can't get every issue over the finish line.
