### ISSUE TITLE
Recent changes in color picker has caused incompatibility with existing picker

### ISSUE THREAD

**Issue by drummerboy46** [umbraco/Umbraco-CMS#3993]
1. Upgraded project to 7.13 from 7.12.4.
2. Cleared dependency cache (increased revision)
3. Tried to edit a color picker in the back office (currently embedded in nested content) and got following JS error....

TypeError: Cannot create property 'value' on string 'e93f6f'
    at Ub (DependencyHandler.axd

4. Tried creating a new nested content item, picker works as expected.

**Comment by nul800sebastiaan** [comment]
@drummerboy46 I hear the same on the forum but I can't reproduce, am I doing it wrong? 


https://our.umbraco.com/forum/using-umbraco-and-getting-started/95232-713-issues

Also, if you go into web.config and set `debug="true"` do you get a better javascript error? In any case, can you send some of the lines of javascript at which things seem to break?

**Comment by nul800sebastiaan** [comment]
Workaround posted here: https://our.umbraco.com/forum/using-umbraco-and-getting-started/95232-713-issues#comment-301098

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/issues/3993

**Comment by nul800sebastiaan** [comment]
We could test if it's a hex value, really, but this works for now.

We know that all old values were stored as a hex, so this is okay for upgraders. All other values are stored as a json which looks a bit like `{ value: "e93f6f", label: "My fun color" }`

**Comment by ronaldbarendse** [comment]
Seems like a simple change that makes the code cleaner and makes the intent clearer (all strings should be converted to objects)... If (for some reason) the value isn't exactly 6 characters long, it would still throw the error.

**Comment by nul800sebastiaan** [comment]
Sure, while we know definitively that always produced 6 chars, this works fine too.. though it will still crash with the same error if it's not 6 chars ;-)

Anyway, it's updated now, had to move the fix to the correct function anyway.  https://github.com/umbraco/Umbraco-CMS/commit/d69f0fe9ddf8c8d37f4fe4d27b5974cddf4f88d3

**Comment by ronaldbarendse** [comment]
Great, it's always good to be on the defensive side, even for these small changes!
