### ISSUE TITLE
v8: Selecting rollback version returns console errors

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4426]
When selectig a rollback version from the dropdown, it seems to return console errors.

![image](https://user-images.githubusercontent.com/2919859/52272736-f1f08780-2947-11e9-9412-93260723308f.png)

The select input has the following `track by`:

```
<select class="input-block-level" ng-model="vm.selectedVersion" ng-options="version.displayValue for version in vm.previousVersions track by version.versionId">
</select>
```

From the console errors it seems the `version.versionId` is not unique?

**Comment by nul800sebastiaan** [comment]
Looks like the same issue as: https://github.com/umbraco/Umbraco-CMS/issues/4426

Hopefully should be fixed with the PR attached to that.

**Comment by nul800sebastiaan** [comment]
Whoops, wrong link: https://github.com/umbraco/Umbraco-CMS/issues/4405

**Comment by bjarnef** [comment]
@nul800sebastiaan okay, I didn't triggered the rollback at this state, just when selecting the rollback version from the dropdown.

**Comment by bjarnef** [comment]
@nul800sebastiaan actually I think this is a different issue.

The duplicate seems to be caused by this `track by` in rollback view:

```
<table class="table table-condensed table-bordered">
    <tbody>
        <tr>
            <td class="bold">Name</td>
            <td>
                <span ng-repeat="part in vm.diff.name">
                    <ins ng-if="part.added">{{part.value}}</ins>
                    <del ng-if="part.removed">{{part.value}}</del>
                    <span ng-if="!part.added && !part.removed">{{part.value}}</span>
                </span>
            </td>
        </tr>
        <tr ng-repeat="property in vm.diff.properties track by property.alias">
            <td class="bold">{{property.label}}</td>
            <td ng-class="{'pre-line': property.isObject, 'word-wrap': !property.isObject}">
                <span ng-repeat="part in property.diff">
                    <ins ng-if="part.added">{{part.value}}</ins>
                    <del ng-if="part.removed">{{part.value}}</del>
                    <span ng-if="!part.added && !part.removed">{{part.value}}</span>
                </span>
            </td>
        </tr>
    </tbody>
</table>
```

E.g. `vm.diff.properties` returns something like this:

```
[{
		"alias": "interval",
		"label": "Interval",
		"diff": [{
				"value": "15,60",
				"count": 3
			}
		],
		"isObject": false
	}, {
		"alias": "intro",
		"label": "Intro",
		"diff": [{
				"value": "A sample description...",
				"count": 6
			}
		],
		"isObject": false
	}, {
		"alias": "usp",
		"label": "USP",
		"diff": [{
				"count": 12,
				"value": "[\n {\n \"value\": \"Cool stuff"
			}, {
				"count": 6,
				"removed": true,
				"value": "\",\n \"$$hashKey\": "
			}, {
				"count": 1,
				"value": "\""
			}, {
				"count": 4,
				"removed": true,
				"value": "object:172\""
			}, {
				"count": 13,
				"value": "\n },\n {\n \"value\": \"Low prices"
			}, {
				"count": 6,
				"removed": true,
				"value": "\",\n \"$$hashKey\": "
			}, {
				"count": 1,
				"value": "\""
			}, {
				"count": 4,
				"removed": true,
				"value": "object:173\""
			}, {
				"count": 13,
				"value": "\n },\n {\n \"value\": \"Fast delivery"
			}, {
				"count": 6,
				"removed": true,
				"value": "\",\n \"$$hashKey\": "
			}, {
				"count": 1,
				"value": "\""
			}, {
				"count": 4,
				"removed": true,
				"value": "object:174\""
			}, {
				"count": 4,
				"value": "\n }\n]"
			}
		],
		"isObject": true
	}, {
		"alias": "persons",
		"label": "Persons",
		"diff": [{
				"value": "[]",
				"count": 1
			}
		],
		"isObject": true
	}, {
		"alias": "image",
		"label": "Image",
		"diff": [{
				"count": 114,
				"value": "{\n \"src\": \"/media/d57dc43810094d4cb6a2eccf585ce8ff/bf744844b8784493ae6f3300ef778cf3/unicorn.jpg\",\n \"focalPoint\": {\n \"left\": 0.5,\n \"top\": 0.49994445061659815\n },\n \"crops\": [\n {\n \"alias\": \"Portrait\",\n \"width\": 80,\n \"height\": 120,\n \"coordinates\": {\n \"x1\": 0.24238536082869178,\n \"y1\": 0.09630117872642761,\n \"x2\": 0.6291985539640543,\n \"y2\": 0.6468956780030988\n "
			}, {
				"count": 1,
				"removed": true,
				"value": "},"
			}, {
				"count": 1,
				"added": true,
				"value": "}"
			}, {
				"count": 1,
				"value": "\n "
			}, {
				"count": 10,
				"removed": true,
				"value": "\"$$hashKey\": \"object:219\"\n "
			}, {
				"count": 31,
				"value": "},\n {\n \"alias\": \"Landscape\",\n \"width\": 120,\n \"height\": 40,\n \"coordinates\": null"
			}, {
				"count": 1,
				"removed": true,
				"value": ","
			}, {
				"count": 1,
				"value": "\n "
			}, {
				"count": 10,
				"removed": true,
				"value": "\"$$hashKey\": \"object:220\"\n "
			}, {
				"count": 5,
				"value": "}\n ]\n}"
			}
		],
		"isObject": true
	}
]
```

**Comment by bjarnef** [comment]
Okay, it tried removing the three `track by` in the rollback view, but it seems I still get this console error.

**Comment by bergmania** [comment]
@bjarnef, can you describe steps to reproduce?

**Comment by bjarnef** [comment]
@bergmania click "rollback" button, on init there isn't console errors, but after selection a rollback version from dropdown it seems to throw a console error.

**Comment by bergmania** [comment]
@bjarnef , I can't reproduce. How is the document type

**Comment by bjarnef** [comment]
@bergmania it was a "Home" document type with some different properties using textstring, textarea, slider, media picker, repeatable textstrings, image cropper.

**Comment by bergmania** [comment]
@bjarnef , thanks i can reproduce. I looks to be when I add `repeatable textstrings` the error occurs

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4574

**Comment by warrenbuckley** [comment]
Connects #4574

**Comment by warrenbuckley** [comment]
Merged in
