### ISSUE TITLE
Images are missing and can't refresh Memory Cache

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#7868]
We can't refresh our Memory Cache on a V8-website. We first saw this error on Umbraco 8.5.5 but it's still present in 8.6.0.

The symptoms are similar to this https://github.com/umbraco/Umbraco-CMS/issues/7766 and this https://github.com/umbraco/Umbraco-CMS/issues/7756 but in our case a "Save" of the Media Item will not update the cache either.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6, and also when we where running on 8.5.5. The site has been upgrade from at least 8.4 before.

### Specifics
We had issues on Umbraco 8.5.5 that the cache suddenly would not update, when triggering a Refresh (from the Settings-section Dashboard) we got an error message. 

Since 8.6 was released today we figured an upgrade maybe could solve this, but after the upgrade the symptoms are still there.

A strange thing is that the cache is populated correctly for us after a restart, so basiclly:

1. Start the site and things works
2. Go to Backoffice / Settings and hit "Refresh Memory Cache"
3. Error message below are shown
4. Almost all media-pickers resolve to "null" on the front end
5. Restart the site by touching web.config
6. All images works again on the front end.
7. Try step 2 again and we'll get the same error.

Error message: 

```
An error occured
Object reference not set to an instance of an object.

Exception Details
System.NullReferenceException: Object reference not set to an instance of an object.

at Umbraco.Web.PublishedCache.NuCache.ContentStore.AddTreeNodeLocked(ContentNode content, LinkedNode`1 parentLink) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentStore.cs:line 1031
   at Umbraco.Web.PublishedCache.NuCache.ContentStore.SetAllLocked(IEnumerable`1 kits) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\ContentStore.cs:line 762
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.LoadMediaFromDatabaseLocked(IScope scope, Boolean onStartup) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 470
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.NotifyLocked(IEnumerable`1 payloads, Boolean& anythingChanged) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 792
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.Notify(JsonPayload[] payloads, Boolean& anythingChanged) in D:\a\1\s\src\Umbraco.Web\PublishedCache\NuCache\PublishedSnapshotService.cs:line 768
   at Umbraco.Web.Cache.MediaCacheRefresher.Refresh(JsonPayload[] payloads) in D:\a\1\s\src\Umbraco.Web\Cache\MediaCacheRefresher.cs:line 46
   at Umbraco.Core.Sync.ServerMessengerBase.Deliver[TPayload](ICacheRefresher refresher, TPayload[] payload) in D:\a\1\s\src\Umbraco.Core\Sync\ServerMessengerBase.cs:line 295
   at Umbraco.Web.Cache.DistributedCache.RefreshByPayload[TPayload](Guid refresherGuid, TPayload[] payload) in D:\a\1\s\src\Umbraco.Web\Cache\DistributedCache.cs:line 83
   at Umbraco.Web.Cache.DistributedCacheExtensions.RefreshAllMediaCache(DistributedCache dc) in D:\a\1\s\src\Umbraco.Web\Cache\DistributedCacheExtensions.cs:line 163
   at Umbraco.Web.Cache.DistributedCacheExtensions.RefreshAllPublishedSnapshot(DistributedCache dc) in D:\a\1\s\src\Umbraco.Web\Cache\DistributedCacheExtensions.cs:line 184
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

### Expected result

For the cache to refresh

**Comment by enkelmedia** [comment]
A follow up on this one, the description presented here https://github.com/umbraco/Umbraco-CMS/issues/7766#issuecomment-600742105 was actually close to our issue as well.

Turns out that we tried to move a lot of media files some days ago and got an request timeout, after this we did not notice any issues - everything appeared to be moved. But then later on the issue with the Cache was noticed as picked images was returned as null on the front end.

After finding some nodes in the "umbracoNode"-table that had a path that was not in line with it's parent folder-path we managed to move all these media items to a new folder and the issue disappeared. So it's definitely related to the path of nodes not being in harmony with the path of any of it's parents.

Maybe this is something that should be handled somewhere during the refresh of the cache, I don't have all the insights into how this works but my friend Herman (from Cimplex) made a really hacky core-fix that solved this for him, basically in ContentStore.cs's AddTreeNodeLocked()-method if parent was null he rebuilt the umbracoNode.path, maybe this is something that could be handled by the CMS if it fails to rebuild the cache due to the parent being null?

**Comment by Shazwazza** [comment]
Thanks for reporting. I think we'll need to mark these as duplicates eventually but for now I'll keep both open.

Unfortunately this can't 'just' be solved by doing a null check and then doing some other database write operation. That is only putting a band-aid on another underlying problem. That said, there should be more null checks in place in the content cache code so at least the exception would bubble up sooner and with a more explicit error (not a null ref). 

In both cases, this and #7766 it seems an issue with a moving operation that timed out. The strange thing is that these should all be done within a transaction so if the transaction didn't complete then nothing should have actually been written to the database so that is part of what needs to be figured out... is there an issue with moving. 

* I assume that when you did the move operation, it was just via the back office? 
* I assume you are using Sql server not Sqlce ?

Looking at the mode code it certainly is inline with our other code and will execute in a transaction so seems strange that data could be changed by this operation if it was canceled midway, but i guess something that needs to be looked at. 

The other alternative "fix" (workaround) is to have either/both: a Health check for database data integrity that could do a few checks but most importantly in this case a "Path" check. Perhaps this could be combined with the Cache dashboard during it's Database Cache rebuilding. 

Any chance you have a DB backup of when this was a problem and willing to share so I can replicate? Otherwise do you know what database changes are required to force this problem to occur? I need a way to replicate this to be able to start fixing it.

**Comment by Shazwazza** [comment]
@enkelmedia I've tried to reproduce by manually by having a bunch of media in the database at a 2nd and 3rd level and have changed it's path in the db manually to something invalid. I've then ran the Database Cache rebuild and then the Memory Cache rebuild on the Published Status dashboard but cannot get it to generate a null reference exception.

Having a look through the code I just can't see how it's possible that this would result in a null reference exception because anytime `AddTreeNodeLocked` is called including the above stack trace from [`SetAllLocked`](https://github.com/umbraco/Umbraco-CMS/blob/release-8.6.0/src/Umbraco.Web/PublishedCache/NuCache/ContentStore.cs#L762) we first call `BuildKit` and that is what creates `parent` reference to be passed into `AddTreeNodeLocked` and if parent is null BuildKit fails and when that happens the logic exits without ever calling `AddTreeNodeLocked`. I understand that this is happening but it's just doesn't seem possible in the code which makes this all super strange. 

Another reason i need to be able to replicate this in order to figure out what our options are. If you can share any other info you have on the paths problem that would be much appreciated.

**Comment by enkelmedia** [comment]
Hi!

Thanks for looking at this @Shazwazza! 

I do see that my proposition might not be the right place to fix the problem, a healthcheck would probably also do! Just running that and have a "fix" button that performs the fixes and also maybe display this as a hint if the refresh of the cache goes wrong.

Well, yes the move operation was performed in the Backoffice, we're on SQL Server Express in this case.

We moved about 200+ media files (images) also with nested folders, like this
 
- My Images
   - Images from Stockholm (folder with 50 images)
   - Images from London (folder with 50 images)
   - image_in_the_my_images_folder.jpg (50 files like this)

We move them by selecting all in the list view and "move" to the new "Summer Photos"-folder.

- My Images 
    - Summer Photos
      - Images from Stockholm
      - ....

During this move my colleague says that we got a timeout-exception, but the images appeared to be moved and in many cases the path to the image it self was correct in umbracoNode.path, but in our case the path to one of it's parent folders was wrong.

When we tried to refresh the memory cache we got an exception on line 1034 since the parent-variable was null.
![image](https://user-images.githubusercontent.com/1782524/78112041-eab6f380-73fd-11ea-8598-1beaaeda1b6f.png)

When we debugged the path for the "Summer Photos"-folder and it was not correct in the database,  we got this exception for all images under "Summer Photots".

I'm not sure if you updated the db-cache before you tried to update the memory cache? But in our case we did.

I've talked to our client and they are willing to share a backup that we took before we fixed this yesterday, it's was when we where still on v8.5.5 but I guess that's fine? They where a little concerned about user data so I guess I can just change the email of all the users. Do you need the whole database or just some tables? Reach out to me markus@obviuse.se and I'll make sure to send it to you in a suitable manner.

**Comment by teeto** [comment]
@Shazwazza the operation was done using the backoffice on the website hosted on azure.
The database is Azure SQL.
The project version was Umbraco 8.5.4
I have a backup with the problem and updated it to 8.6.0 and the problem still is happening.
I can send you the backup up, is 16MB zipped. How do you want me to send it to you?

**Comment by Shazwazza** [comment]
Hi @teeto if you can email me at shannon@umbraco.com that would be wonderful. @enkelmedia are you able to send me your at my email address too?

**Comment by teeto** [comment]
Thanks @Shazwazza  i have just sent it

**Comment by Shazwazza** [comment]
Thanks for your DBs. I can reproduce the issue and can see where a null check is needed. However, this doesn't solve the problem. The null check will prevent things from exploding but it will mean tons of your media is missing from the cache and you'll end up with tons of warnings in the log. 

It's a step in the right direction but the underlying problem as you say is that the umbracoNode path's are wrong in some cases. What I cannot figure out is how that is possible. Regardless of if there was an SQL timeout or some other error where the app needed to be terminated, each move operation is performed within a SQL transaction. If one of those operations failed, even if the single operation was for a folder with 500 descendants, the whole thing would roll back and nothing would be changed. 

The code for moving stuff has tests for it and I've run my own tests and the path and level are fine, however in replicating this error, the path and level are incorrect. 

Is it possible this data could have been wrong before these move operations? Is there anything else you can tell me that led up to this problem? i.e. has this site been around for a long time and upgraded from older versions?

**Comment by Shazwazza** [comment]
Any chance either of you have a DB backup from before the move happened?

**Comment by teeto** [comment]
I have just sent you another backup before the move.

**Comment by Shazwazza** [comment]
Fantastic, thanks @teeto. I've created a health check on my local build which verifies all paths for content/media. I can confirm that your original database has no corrupt paths before the move. I've actually been able to reproduce the path corruption issue by following your instructions in your email. This is both good and bad news. Good news that I can replicate which means I have some way to fix this. Bad news is that there is an issue somewhere in the logic of moving media (and probably content) that corrupts paths or levels in umbracoNode table.

I'll post more info when I have it.

**Comment by Shazwazza** [comment]
I've found the problem and have created a draft PR which you can find here with a full explanation https://github.com/umbraco/Umbraco-CMS/pull/7907

I'll close this issue and keep the PR open which will be the description that shows up in release notes. Many many thanks for the help in getting to the bottom of this one. Feel free to keep comments here or on the PR.

**Comment by enkelmedia** [comment]
Waow! Great work @Shazwazza!

**Comment by teeto** [comment]
Thanks @Shazwazza 
Could you test on my DBs why creating or modifying a document type is so slow?
When i had the problem of corrupted media i got an error when reloading the cache, which i guess is the same error i got when modifying or creating a document type. I dont now if both operations are related. Now with the error fixed it still is slow, not that much but may be 10-15 sec. May be is reloading the cache and if lots of content it gets slow?

**Comment by Shazwazza** [comment]
@teeto yes i will have a look at that also once this other investigation/fix is completed and i'll see if i can replicate.

**Comment by nvdeveloper** [comment]
@Shazwazza I am getting the same error in my site, I upgraded it to 8.6.1. I tried the SQL script in #7907. But still getting the same error when trying to update the memory cache. 

Is there anything else I can try?

**Comment by Shazwazza** [comment]
@nvdeveloper did the sql script report problems? Did you commit the transaction?

**Comment by nvdeveloper** [comment]
@Shazwazza doh, I missed that the comit was commented out. Thanks, I think that sorted it.
