### ISSUE TITLE
Block List Editor (Nested) Crashes and unresponsive.

### ISSUE THREAD

**Issue by robjakedorsett** [umbraco/Umbraco-CMS#9667]
I'm having an issue where the back office is completely crashing when I'm trying to populate a block list editor.

This is happening at around 5 levels of nesting within (though I have been able to get it to happen at 4). 
There aren't any console logs, or network errors happening. 

## Umbraco version

I am seeing this issue on Umbraco version: 8.10.1 & 8.9.1

Steps to Reproduce:
- Create a Doc type - HomePage with a picker for Block List "Tabbed Content" 
- Create a Doc type  (Element type) - Tabbed Content, with a picker for Block List "Tab"
- Create a Doc type (Element type) - Tab, with a picker for Block List "Full Width Layout"
- Create a Doc type (Element type) - Full WIdth Layout with a picker for "Component"
- Create a Doctype (Element type) - "Component" with a picker for "Component Item"
- Create a Doctype (Element type) - "Component Item" with the properties - Url Picker (Mandatory) & Media Picker (Mandatory)

The Block list configs are all default and empty, excluding the "Content Model" ofcourse

Also worth noting that all the doc types have enabled varient by culture

**Comment by robjakedorsett** [comment]
![image](https://user-images.githubusercontent.com/47298040/104789303-931b2600-578c-11eb-9338-deac772aa99d.png)

**Comment by nathanwoulfe** [comment]
@robjakedorsett can you provide some more detail - steps to reproduce, your block config, any console errors etc. Anything that might be useful for tracking down the cause and determining if it's a bug or an implementation issue.

**Comment by robjakedorsett** [comment]
Hi @nathanwoulfe I have editted my original comment to include replication steps and block list configs ( they are all default)

**Comment by robjakedorsett** [comment]
I have been playing around with this, this morning, and I have discovered that it seems to occur when properties are set to mandatory,  So I assume it's got something to do with the validation javascript somehow

**Comment by nathanwoulfe** [comment]
Magic, thanks @robjakedorsett. Definitely looks a bit busted in the gif...

**Comment by nul800sebastiaan** [comment]
I think this is the same problem as https://github.com/umbraco/Umbraco-CMS/issues/9360

@nielslyngsoe & @madsrasmussen can you confirm that the PR for that one also fixes this problem please?

**Comment by nul800sebastiaan** [comment]
Alright, it's confirmed that this is fixed with PR https://github.com/umbraco/Umbraco-CMS/pull/9677 which will be available in patch releases for 8.7, 8.8, 8.9, 8.10 and in the final release of 8.11, all coming next week.

**Comment by robjakedorsett** [comment]
Great news.

Thank you guys!

**Comment by HalldorLyngmo** [comment]
I'm seeing the same issue on v8.12.0 where the browser will start to slow down before the tab crashes.
This is with mandatory properties and going 3+ levels deep. Removing the mandatory attribute on the properties solves the issue.

Reproduction:

- Create a Doc type (Element type) - With a text string (mandatory), Url Picker (Mandatory) and block list editor where you can pick this element type after it has been saved. Create a loop.
- Create a Doc type (Allowed as root) - With a block list editor where you pick the previous element type
- Everything else is as by default

![block-list-editor-freezing](https://user-images.githubusercontent.com/42831978/111131076-2ea3f980-8578-11eb-8996-9aaf3a26be0b.gif)

**Comment by truunk** [comment]
I can confirm this is still happening with 8.12.2, 3 levels deep.  It only seems to happen when the Link Picker is set to mandatory, other mandatory fields seem fine.

**Comment by nul800sebastiaan** [comment]
Fixed for the upcoming 8.14.0 in: https://github.com/umbraco/Umbraco-CMS/pull/10134

**Comment by DerickVanDerSandt** [comment]
@nul800sebastiaan any idea on when 8.14.0 will be released for Umbraco Cloud?

**Comment by nul800sebastiaan** [comment]
@DerickVanDerSandt About 6 hours ago 😄
